# https://blog.idrsolutions.com/how-to-sync-bitbucket-repo-to-github/

image: atlassian/default-image:4

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:wyverr/streamlined.git
          - cd streamlined.git
          - git push --mirror git@github.com:SkipTheDragon/streamlined.git
