image: php:8.1

definitions: 
  steps:
    - step: &save-envs
        name: "Save env variables"
        script:
          - echo "export SERVER_IP=$SERVER_IP"   >  .envs
          - echo "export SERVER_USERNAME=$SERVER_USERNAME"  >>  .envs
          - echo "export SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY"      >>  .envs
          - echo "export REPO_SSH_PRIVATE_KEY=$REPO_SSH_PRIVATE_KEY"      >>  .envs

        artifacts:
          - .envs
    - step: &deployment
        script:
          - source .envs
          
pipelines:
    default:
        - step:
            <<: *save-envs
            deployment: production
        - step:
            <<: *deployment
            image: atlassian/default-image:latest
            name: Manual step
            script:
              - cd $BITBUCKET_CLONE_DIR/app/bundle/StreamlinedBundle
              - git init
              - echo $REPO_SSH_PRIVATE_KEY
              - echo $REPO_SSH_PRIVATE_KEY | base64 --decode > ~/.ssh/id_rsa
              - git remote add origin git@github.com:SkipTheDragon/streamlined.git
              - git add .
              - git commit -m "$BITBUCKET_COMMIT"
              - git push --set-upstream origin main

    branches:
      release:
        - step:
            <<: *save-envs
            deployment: production
        - step:
            <<: *deployment
            name: Deploy Demo to Prod
            script:
              - source .envs
              - apt-get update && apt-get install -y openssh-client rsync
              - echo $SSH_PRIVATE_KEY | base64 --decode > ~/.ssh/id_rsa
              - chmod 600 ~/.ssh/id_rsa
              - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
              - rsync -r --delete-after --quiet $BITBUCKET_CLONE_DIR/app/ $SERVER_USERNAME@$SERVER_IP:/home/demo.wyverr.com/streamlined.demo.wyverr.com/
              - ssh $SERVER_USERNAME@$SERVER_IP 'cd /home/demo.wyverr.com/streamlined.demo.wyverr.com/ && APP_ENV=prod composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction'
        - step:
            <<: *deployment
            name: Deploy Docs to Prod
            image: node:18.16-bullseye
            script:
              - source .envs
              - apt-get update && apt-get install -y openssh-client rsync
              - echo $SSH_PRIVATE_KEY | base64 --decode > ~/.ssh/id_rsa
              - chmod 600 ~/.ssh/id_rsa
              - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
              - cd $BITBUCKET_CLONE_DIR/app/bundle/StreamlinedBundle/src/Resources/docs && npm i && npm install -D tailwindcss@latest postcss@latest autoprefixer@latest && npm run build
              - rsync -r --delete-after --quiet $BITBUCKET_CLONE_DIR/app/bundle/StreamlinedBundle/src/Resources/docs/build/ $SERVER_USERNAME@$SERVER_IP:/home/docs.wyverr.com/streamlined.docs.wyverr.com/
