image: php:8.1

pipelines:
  default:
    - step:
        name: Deploy Demo to Prod
        deployment: production
        script:
          - apt-get update && apt-get install -y openssh-client rsync
          - echo $SSH_PRIVATE_KEY | base64 --decode > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa
          - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          - rsync -r --delete-after --quiet $BITBUCKET_CLONE_DIR/app/ $SERVER_USERNAME@$SERVER_IP:/home/demo.wyverr.com/streamlined.demo.wyverr.com/
          - ssh $SERVER_USERNAME@$SERVER_IP 'cd /home/demo.wyverr.com/streamlined.demo.wyverr.com/ && APP_ENV=prod composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction'

